### ISSUE TITLE
Create Payments/Sales with line items detailed  

### ISSUE THREAD

**Issue by rcrespo808** [2Checkout/2checkout-java#8]
Hello.
I am trying to test registering a payment with line items detailed in order to have the recurring payment functionality accessible, but I find no documentation on how to register a detailed order as such.

I did assume something like [this](https://www.2checkout.com/documentation/checkout/parameters/) would be usable; but in testing I have realized it is not.

Is there any way to do this?
if not, are there plans top implement this and an alternative I could look into?

**Comment by robertop87** [comment]
@craigchristenson any update about this?

**Comment by craigchristenson** [comment]
Sorry for the delay in getting back to you. Lineitems need to be passed as an array of objects and the total should be omitted like below:

```java
            HashMap<String, String> billing = new HashMap<String, String>();
            billing.put("name", "Testing Tester");
            billing.put("addrLine1", "123 Test St");
            billing.put("city", "Columbus");
            billing.put("state", "Ohio");
            billing.put("country", "USA");
            billing.put("zipCode", "43230");
            billing.put("email", "tester@2co.com");
            billing.put("phone", "555-555-5555");

            HashMap<String, String> item = new HashMap<String, String>();
            item.put("name", "Example Subscription");
            item.put("recurrence", "1 Month");
            item.put("duration", "Forever");
            item.put("price", "1.00");

            ArrayList<HashMap<String, String>> lineItems = new ArrayList<>();
            lineItems.add(item);

            HashMap<String, Object> request = new HashMap<String, Object>();
            request.put("sellerId", "<your-seller-id>");
            request.put("merchantOrderId", "test123");
            request.put("token", "<token>");
            request.put("currency", "USD");
            request.put("billingAddr", billing);
            request.put("lineItems", lineItems);

            Authorization response = TwocheckoutCharge.authorize(request);
```

**Comment by rcrespo808** [comment]
I am getting an error when including "lineItem" data and no "total" data. Note I have no errors when test data is sent with "total" data, nevertheless, line item data is ignored.
the following is example data used and the response:
REQUEST:
{
   "lineItems":[
      {
         "recurrence":"1 week",
         "duration":"1 year",
         "price":"10,50",
         "name":"Sale of Product 1001"
      }
   ],
   "privateKey":"13EFFAD8-1B26-4D55-9C0E-698F64701E83",
   "sellerId":"901349571",
   "currency":"USD",
   "merchantOrderId":"SBOnepayment",
   "billingAddr":{
      "country":"BOL",
      "city":"Santa Cruz",
      "phone":"33575050",
      "addrLine1":"Buen Retiro 120",
      "name":"Test Buyer",
      "email":"test@test.com"
   },
   "token":"MTEzNDExYWUtNWUxYS00ZTI4LTk5ZjItNzEzYjFkNmYyMjJk"
}
RESPONSE:
{
  "validationErrors": null,
  "response": null,
  "exception": {
    "errorMsg": "Bad request - parameter error",
    "httpStatus": "400",
    "exception": false,
    "errorCode": "400"
  }
}
